language: node_js

node_js:
- stable

cache:
  yarn: true

before_install:
- npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
- yarn config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}

deploy:
- provider: script
  script: yarn publish:release --canary --preid=$TRAVIS_BRANCH.$TRAVIS_JOB_NUMBER --dist-tag=$TRAVIS_BRANCH --yes
  skip_cleanup: true
  on:
    branch: master
    tags: false
    repo: ringcentral/ringcentral-javascript
- provider: script
  script: yarn publish:release $TRAVIS_TAG --yes
  skip_cleanup: true
  on:
    tags: true
    repo: ringcentral/ringcentral-javascript
